# Generated by Django 5.0.6 on 2026-09-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Authorized', 'Authorized'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired'), ('Refunded', 'Refunded')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Authorized', 'Authorized'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired'), ('Refunded', 'Refunded')], default='Pending', max_length=30),
        ),
    ]
