# Generated by Django 5.0.6 on 2026-07-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='banners',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
