# Generated by Django 5.0.6 on 2026-06-19 04:41

import common.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', models.CharField(default=common.utils.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('order_items', models.JSONField(default=list)),
                ('shipping_address', models.JSONField(default=dict)),
                ('payment_info', models.JSONField(blank=True, default=dict)),
                ('items_price', models.FloatField(default=0)),
                ('tax_price', models.FloatField(default=0)),
                ('shipping_price', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('order_status', models.CharField(choices=[('Placed', 'Placed'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed', max_length=20)),
                ('status_history', models.JSONField(blank=True, default=list)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='orders_user_id_535113_idx'), models.Index(fields=['order_status'], name='orders_order_s_0d3802_idx'), models.Index(fields=['-created_at'], name='orders_created_b25042_idx')],
            },
        ),
    ]
