# Generated by Django 5.0.6 on 2026-06-19 04:41

import common.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', models.CharField(default=common.utils.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Smartphones', 'Smartphones'), ('Accessories', 'Accessories'), ('Smart Watches', 'Smart Watches'), ('Earbuds', 'Earbuds'), ('Chargers', 'Chargers'), ('Power Banks', 'Power Banks')], max_length=40)),
                ('description', models.TextField()),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('images', models.JSONField(blank=True, default=list)),
                ('original_price', models.FloatField()),
                ('offer_price', models.FloatField()),
                ('discount', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('num_reviews', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('flash_sale', models.BooleanField(default=False)),
                ('num_sold', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand'], name='products_brand_b2547a_idx'), models.Index(fields=['category'], name='products_categor_fce6e6_idx'), models.Index(fields=['offer_price'], name='products_offer_p_989393_idx'), models.Index(fields=['-rating'], name='products_rating_33245e_idx'), models.Index(fields=['-num_sold'], name='products_num_sol_12a1c7_idx'), models.Index(fields=['-discount'], name='products_discoun_3789af_idx'), models.Index(fields=['-created_at'], name='products_created_a77fb9_idx'), models.Index(fields=['is_featured'], name='products_is_feat_19b203_idx'), models.Index(fields=['flash_sale'], name='products_flash_s_64c15a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('_id', models.CharField(default=common.utils.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
