# Generated by Django 5.0.6 on 2026-09-10 10:10

import common.utils
import django.core.validators
import django.db.models.deletion
import products.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('49.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='ProductUploadSession',
            fields=[
                ('_id', models.CharField(default=common.utils.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('token', models.CharField(default=products.models.generate_session_token, max_length=64, unique=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_upload_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductUploadItem',
            fields=[
                ('_id', models.CharField(default=common.utils.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('storage_key', models.CharField(max_length=500)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, default='image/jpeg', max_length=100)),
                ('is_committed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.productuploadsession')),
            ],
            options={
                'db_table': 'product_upload_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('_id', models.CharField(default=common.utils.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('storage_key', models.CharField(blank=True, default='', max_length=500)),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, default='image/jpeg', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product')),
            ],
            options={
                'db_table': 'product_images',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['product', 'sort_order'], name='product_ima_product_66d32e_idx'), models.Index(fields=['product', 'is_primary'], name='product_ima_product_c8c86a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_image_per_product'),
        ),
        migrations.AddIndex(
            model_name='productuploadsession',
            index=models.Index(fields=['token'], name='product_upl_token_fd8618_idx'),
        ),
        migrations.AddIndex(
            model_name='productuploadsession',
            index=models.Index(fields=['user', 'status'], name='product_upl_user_id_06d919_idx'),
        ),
    ]
